### ISSUE TITLE
Change all occurences of Murder.Core.Vector2 into System.Numerics.Vector2

### ISSUE THREAD

**Issue by saint11** [isadorasophia/murder#12]
And create all appropriate helpers as extensions.
Using System.Numerics.Vector2 will allow us to use hardware acceleration with vector math and will make things easier to integrate with other libraries.

**Comment by dgoelitz** [comment]
This project looks awesome! I noticed this because of the "good first issue" tag. I've never contributed to open source before but I've just used C# in my day job for two years. I'll give it a whirl if that's ok.

**Comment by saint11** [comment]
Sounds great :) Feel free to ask for help here or on the discord if you need
