### ISSUE TITLE
Tile grid size is hardcoded

### ISSUE THREAD

**Issue by saint11** [isadorasophia/murder#17]
Check `Grid.cs`.
`CellSize` is hardcoded, the default value should be available to change on GameProfile and each scene should have it's own grid size.

**Comment by heytherewill** [comment]
If you're not on it yet, I'll take this over since I need it for my grid which is 16x16.

When you say `Each scene should have its own grid size`, do you mean adding it directly to the Scene class or somewhere else more accessible to systems, like `RenderContext`?
